### PR TITLE
begin SDS1104X-E port

### PR DESCRIPTION
**Pull request by mandl**
Hello Andrew, i did the first version for Siglent SDS1104x-E. Hope i did not break anything..
Regards Stefan

### CODE REVIEW

**Comment by azonenberg** [comment]
This looks to be duplicating a lot of the work in #529. You should sync with @dannas to avoid wasting time on stuff that's already being done.

**Comment by mandl** [comment]
Yes - it  is based on @dannes  code with some fixes - it works now with LAN. Regards Stefan

**Comment by mubes** [comment]
Hi Stefan, would you mind adding in the header of the file what is working and what isn't (and separating out the 2000 and 1104x cases) so we know what still needs to be done?  I think there is a lot of tidying we can do of the various cases (especially since we'll want to support more scopes later) but the main thing is to get everything working and then tidy up from there...there ain't too much point in polishing something that doesn't work :-)

**Comment by mubes** [comment]
I'm a bit confused. I've merged this with the switch fixes and posted it into the discord twice now, and there are still versions of this patch being proposed that don't take account of the merges. Can you please reconcile them? I don't really understand why this patch wasn't an extension of @dannas proposal in #535 but given were we are let's get everything tidied up and aligned so it can go back into master.

**Pull request closed without merging**
